In [27]:
import numpy as np

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [28]:
print(type(arr1))

<class 'numpy.ndarray'>


In [29]:
arr1.shape

(3,)

In [30]:
arr2 = np.array([[1,2,3],[3,4,5]])
print(type(arr2))

<class 'numpy.ndarray'>


In [31]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [32]:
arr2.shape

(2, 3)

In [33]:
arr2[1][2]

5

In [34]:
countries = np.array(['kenya','uganda','ghana','china'])
print(countries)

['kenya' 'uganda' 'ghana' 'china']


In [35]:
arr3 = np.arange(0,20,3)
print(arr3)

[ 0  3  6  9 12 15 18]


In [36]:
randomn = np.random.rand (10)
randomn

array([0.06806427, 0.17333961, 0.90181974, 0.91486156, 0.62006674,
       0.33590198, 0.56116355, 0.613825  , 0.7524086 , 0.58186536])

In [37]:
rad =np.random.rand(1,2)
rad

array([[0.76415807, 0.5050233 ]])

In [38]:
arry = np.random.randint(-10,50,4)
arry

array([ 2,  4, 10, 12])

In [39]:
arry +50

array([52, 54, 60, 62])

In [40]:
np.diag(arry)

array([[ 2,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 12]])

In [42]:
np.cos(arry)

array([-0.41614684, -0.65364362, -0.83907153,  0.84385396])

In [43]:
arry

array([ 2,  4, 10, 12])

In [44]:
randomn

array([0.06806427, 0.17333961, 0.90181974, 0.91486156, 0.62006674,
       0.33590198, 0.56116355, 0.613825  , 0.7524086 , 0.58186536])

In [45]:
np.mean(randomn)

0.5523316407564085

In [47]:
np.std(randomn)

0.2697984499867939

In [48]:
np.var(randomn)

0.07279120361527654

In [49]:
np.median(randomn)

0.597845178652445

In [66]:
ex =np.random.rand(8)
ex

array([0.62507063, 0.58093177, 0.27411022, 0.86369496, 0.1556661 ,
       0.3924848 , 0.20034523, 0.50092626])

In [75]:
ex[3:: ]

array([0.86369496, 0.1556661 , 0.3924848 , 0.20034523, 0.50092626])

In [77]:
np.sort(ex, axis = 0)

array([0.1556661 , 0.20034523, 0.27411022, 0.3924848 , 0.50092626,
       0.58093177, 0.62507063, 0.86369496])

In [81]:
arr = np.array([4, 5, 6, 7, 8])
arr

array([4, 5, 6, 7, 8])

In [83]:
arr5 = np.append(arr,9)
arr5


array([4, 5, 6, 7, 8, 9])

In [85]:
insrt = np.insert(arr5, 0, [1, 2, 3])
insrt


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
delet = np.delete(insrt, [1,3,8])
delet

array([1, 3, 5, 6, 7, 8])

In [91]:
arrc = delet.copy()
arrc

array([1, 3, 5, 6, 7, 8])

In [103]:
arr1 = np.array([[ 1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7, 8]])
cat = np.concatenate((arr1,arr2), axis =1 )
cat


array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [101]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [106]:
arr1 = np.array([1, 2, 3, 4, 1, 4, 3, 5, 6, 5, 2])
arr2 = np.unique(arr1)
arr2

array([1, 2, 3, 4, 5, 6])

In [111]:
#return counts on the unique values

uniques, counts = np.unique(arr1, return_counts= True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 2 2 1]


In [114]:
#intersection, differentiation or neither 

arra= np.array([1, 2, 3, 4, 5])
arrb = np.array([3, 4, 5, 6 , 7])
print(np.intersect1d(arra,arrb))
print(np.union1d(arra, arrb))
print(np.setdiff1d(arra, arrb))
print(np.setxor1d(arra, arrb))








[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]
